development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: admin
  password: "Admin@123$%"

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: admin
  password: "Admin@123$%"
